repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
        exclude: ".*\\.xml$"
      - id: pretty-format-json
        args: [--autofix, --no-sort-keys]
        files: (package\.json|tsconfig\.json)$
        types: [file]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.4
    hooks:
      - id: ruff-format
        name: python format
      - id: ruff
        alias: ruff-check
        name: python lint
        args: [--fix]

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "v9.6.0"
    hooks:
      - id: eslint
        files: \.(js|ts|mjs)$
        types: [file]
        args: [--fix]
        additional_dependencies:
          - "eslint@^8.57.0"
          - "prettier@3.3.3"
          - "eslint-plugin-prettier@^5.1.3"
          - "eslint-config-prettier@^9.1.0"
          - "@typescript-eslint/eslint-plugin@^7.1.0"
          - "@typescript-eslint/parser@^7.1.0"
