[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "lsp_server"
dynamic = ["version", "description"]
requires-python = "~=3.12.3"
dependencies = [
    "pygls>=1.3.1",
    "pydantic>=2.9.2",
]

[tool.ruff]
extend = "../../pyproject.toml"
