name: continuous-integration

on:
  push:
    branches: [main]
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"
  pull_request:

jobs:

  pre-commit:

    name: Pre-commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: pip install pre-commit
      - name: Run pre-commit
        run: pre-commit run --all-files

  pytest:

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    name: Pytest (${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Install the latest version of rye
      uses: eifinger/setup-rye@v4
    - name: Run tests
      run: rye test -a

  extension_test:

    name: Test VS Code Extension
    # TODO add macos/windows test matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        cache: 'npm'
        cache-dependency-path: vscode/package-lock.json
    - name: Install the latest version of rye
      uses: eifinger/setup-rye@v4
    - run: rye sync
    - name: Create Python bundle
      run: rye run bundle:prod
    - name: Insall npm dependencies
      working-directory: vscode
      run: npm ci
    - name: Run tests
      working-directory: vscode
      run: npm test

  vsix_package:

    name: Package VS Code Extension (${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: linux-x64
          - os: macos-latest
            target: darwin-arm64
          # TODO add windows distribution
          # - os: windows-latest
          #   target: win32-x64
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        cache: 'npm'
        cache-dependency-path: vscode/package-lock.json
    - name: Install the latest version of rye
      uses: eifinger/setup-rye@v4
    - run: rye sync
    - name: Create Python bundle
      run: rye run bundle:prod
    - name: install vsce
      run: npm install -g vsce
    - name: Insall npm dependencies
      working-directory: vscode
      run: npm ci
    - name: Run vsce package
      working-directory: vscode
      run: vsce package --pre-release -t ${{ matrix.target }} -o extension.${{ matrix.target }}.vsix
    - name: Upload a Build Artifact
      if: github.event_name == 'push'
      uses: actions/upload-artifact@v4
      with:
        name: VS Code Extension (${{ matrix.target }})
        path: vscode/extension.${{ matrix.target }}.vsix

  vsix_publish:

    name: Publish VS Code Extension (${{ matrix.os }})
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
    needs:
      - pre-commit
      - pytest
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: linux-x64
          - os: macos-latest
            target: darwin-arm64
          # TODO add windows distribution
          # - os: windows-latest
          #   target: win32-x64
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        cache: 'npm'
        cache-dependency-path: vscode/package-lock.json
    - name: Install the latest version of rye
      uses: eifinger/setup-rye@v4
    - run: rye sync
    - name: Create Python bundle
      run: rye run bundle:prod
    - name: install vsce
      run: npm install -g vsce
    - name: Insall npm dependencies
      working-directory: vscode
      run: npm ci
    - name: Run vsce publish
      working-directory: vscode
      run: vsce publish -t ${{ matrix.target }} -p ${{ secrets.MARKETPLACE_PAT }}
